name: Deploy to Environment

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # For Linux, use ubuntu-latest
    environment: Test
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4


